### ISSUE TITLE
Mod breaks ripped sheets

### ISSUE THREAD

**Issue by 95Gman** [quarantin/zomboid-spear-traps#6]
No clue how your mod breaks ripped sheets, but it does. This is in the Multiplayer build. I triple checked by running my game vanilla, then with only your mod, then with other mods.

**Comment by quarantin** [comment]
Thank you for the report. This bug has been fixed with release 0.0.4. I was working on new features and in the meantime realized the mod.info was missing the name of the mod, so I made a new release to fix it (0.0.3) but accidentally shipped the files I was working on. Sorry for the inconvenience.
